# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 21:45
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name': 'Reszta', 'verbose_name_plural': 'Inne'},
        ),
        migrations.AlterField(
            model_name='other',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='other',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.utils.image_directory_path, verbose_name='Obraz'),
        ),
        migrations.AlterField(
            model_name='other',
            name='text',
            field=models.TextField(verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='other',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='Tytuł'),
        ),
    ]
