# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 20:59
from __future__ import unicode_literals

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160912_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=articles.models.image_directory_path, verbose_name='Image'),
        ),
    ]
