# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:37
from __future__ import unicode_literals

import articles.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20160913_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=80, unique=True, validators=[articles.utils.validate_title], verbose_name='Title'),
        ),
    ]
