# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Zakazany email',
                'verbose_name_plural': 'Zakazane emaile',
            },
        ),
        migrations.CreateModel(
            name='BannedEmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=100, verbose_name='Domena')),
            ],
            options={
                'verbose_name': 'Zakazana domena',
                'verbose_name_plural': 'Zakazane domeny',
            },
        ),
        migrations.CreateModel(
            name='EmailBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Twoje imię')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Twój adres e-mail')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Zweryfikowany')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Baza emaili',
            },
        ),
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirm_title', models.CharField(blank=True, max_length=255, verbose_name='Tytuł')),
                ('email_confirm', models.TextField(blank=True, verbose_name='Potwierdz email')),
                ('fail_title', models.CharField(blank=True, max_length=255, verbose_name='Tytuł')),
                ('fail', models.TextField(blank=True, verbose_name='Komunikat niepowodznia')),
                ('success_title', models.CharField(blank=True, max_length=255, verbose_name='Tytuł')),
                ('success', models.TextField(blank=True, verbose_name='Komunikat udanej rejestracji')),
                ('cancel_title', models.CharField(blank=True, max_length=255, verbose_name='Tytuł')),
                ('cancel', models.TextField(blank=True, verbose_name='Komunikat udanej rejestracji')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('body', models.TextField(verbose_name='Tekst')),
                ('send', models.BooleanField(verbose_name='Wysłane')),
                ('send_date', models.DateField(verbose_name='Kiedy wysłać')),
            ],
            options={
                'verbose_name': 'Specjalna oferta',
                'verbose_name_plural': 'Specjalne oferty',
            },
        ),
    ]
