# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Twoje imię')),
                ('email', models.EmailField(max_length=254, verbose_name='Twój adres e-mail')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Baza emaili',
            },
        ),
    ]
