# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='send',
            field=models.BooleanField(default=False, verbose_name='Wysłane'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='send_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kiedy wysłać'),
        ),
    ]
