# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20170603_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialoffer',
            old_name='send',
            new_name='is_send',
        ),
    ]
