# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20170603_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='cancel',
            field=models.TextField(blank=True, verbose_name='Komunikat anulowania'),
        ),
    ]
