# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 21:19
from __future__ import unicode_literals

import article.utils
import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True, validators=[article.utils.validate_title], verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('text', models.TextField(verbose_name='Tekst')),
                ('desc', models.CharField(default='', max_length=400, verbose_name='Opis')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to=core.utils.image_directory_path, verbose_name='Obraz')),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'Wersja Robocza'), (1, 'Zaakceptowane'), (2, 'Opublikowane'), (3, 'Ukryte')], default=0, protected=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tags', models.ManyToManyField(related_name='articles', to='tag.Tag', verbose_name='Tagi')),
            ],
            options={
                'verbose_name': 'Artykuł',
                'verbose_name_plural': 'Artykuły',
                'ordering': ['-pk'],
            },
        ),
    ]
