# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='to_publish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kiedy opublikować'),
        ),
    ]
