# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_to_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Wersja Robocza'), (1, 'Zaakceptowane'), (2, 'Opublikowane'), (3, 'Ukryte')], db_index=True, default=0, protected=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='to_publish',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Kiedy opublikować'),
        ),
    ]
