# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 21:07
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170620_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Wersja Robocza'), (1, 'Zaakceptowana'), (2, 'Opublikowane'), (3, 'Ukryte')], default=0, protected=True),
        ),
    ]
