# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160915_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.CharField(default='', max_length=180, verbose_name='Description'),
        ),
    ]
