# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pk'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
