# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 21:45
from __future__ import unicode_literals

import article.utils
import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160921_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pk'], 'verbose_name': 'Artykuł', 'verbose_name_plural': 'Artykuły'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(default='', max_length=400, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.utils.image_directory_path, verbose_name='Obraz'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Opublikuj'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag', verbose_name='Tagi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=80, unique=True, validators=[article.utils.validate_title], verbose_name='Tytuł'),
        ),
    ]
