# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20170223_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='tag.Tag', verbose_name='Tagi'),
        ),
    ]
