# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('slug', models.SlugField(max_length=60, verbose_name='Slug')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='file/', verbose_name='Upload file')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
