# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuessBookEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=70, verbose_name='Autor')),
                ('text', models.CharField(max_length=400, verbose_name='Tekst')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wpis',
                'verbose_name_plural': 'Wpisy',
                'ordering': ['-pk'],
            },
        ),
    ]
