# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0002_auto_20160921_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guessbookentry',
            options={'ordering': ['-pk'], 'verbose_name': 'Wpis', 'verbose_name_plural': 'Wpisy'},
        ),
        migrations.AlterField(
            model_name='guessbookentry',
            name='author',
            field=models.CharField(max_length=70, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='guessbookentry',
            name='text',
            field=models.CharField(max_length=400, verbose_name='Tekst'),
        ),
    ]
