# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0003_auto_20170223_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessbookentry',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Opublikuj'),
        ),
    ]
