# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0004_guessbookentry_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guessbookentry',
            name='publish',
        ),
    ]
