# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Stopka',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nazwa')),
                ('url', models.URLField(unique=True, verbose_name='Url')),
                ('ordering', models.PositiveIntegerField(unique=True, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Nawigacja',
                'verbose_name_plural': 'Nawigacja',
            },
        ),
        migrations.CreateModel(
            name='SiteMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('subheading', models.CharField(max_length=255, verbose_name='Podtytuł')),
                ('description', models.CharField(max_length=255, verbose_name='Opis')),
                ('keywords', models.CharField(max_length=255, verbose_name='Słowa kluczowe')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('image', models.ImageField(upload_to='', verbose_name='Obraz')),
            ],
            options={
                'verbose_name': 'Ustawienia strony',
            },
        ),
    ]
