# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Url')),
                ('ordering', models.PositiveIntegerField(unique=True, verbose_name='Ordering')),
            ],
            options={
                'verbose_name': 'Navigation',
                'verbose_name_plural': 'Navigation',
            },
        ),
    ]
