# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-23 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'verbose_name': 'Nawigacja', 'verbose_name_plural': 'Nawigacja'},
        ),
        migrations.AlterField(
            model_name='navigation',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='ordering',
            field=models.PositiveIntegerField(unique=True, verbose_name='Kolejność'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='url',
            field=models.URLField(unique=True, verbose_name='Url'),
        ),
    ]
