# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-29 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170223_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('github', models.URLField()),
            ],
            options={
                'verbose_name': 'Stopka',
            },
        ),
        migrations.CreateModel(
            name='SiteMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('subheading', models.CharField(max_length=255, verbose_name='Podtytuł')),
                ('description', models.CharField(max_length=255, verbose_name='Opis')),
                ('keywords', models.CharField(max_length=255, verbose_name='Słowa kluczowe')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('image', models.ImageField(upload_to='', verbose_name='Obraz')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
