# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-29 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_footer_sitemeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemeta',
            options={'verbose_name': 'Ustawienia strony'},
        ),
    ]
