# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-29 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170529_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
