# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-11 20:26
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=255, verbose_name='O mnie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=core.utils.avatar_directory_path, verbose_name='Awatar'),
        ),
    ]
