# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 11:49
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=core.utils.avatar_directory_path, verbose_name='Awatar'),
        ),
    ]
