# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-11 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170311_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='O mnie'),
        ),
    ]
